### ISSUE TITLE
When copying from one Cosmos container to another Cosmos container there is a spike in Http 429

### ISSUE THREAD

**Issue by tkumark** [microsoft/CosmicClone#13]
We are trying to migrate data from one container to another container with partitions configured and RU/s set at Database level. The size of the container is 3GB. with 528915 documents. We set the destination throughput to 15000RU/s. 

When we ran this we got a lot of http 429. At the end of the copy Cosmic Clone it gave the below stats. So why is it that I am getting http 429 when it has consumed 8909.58 RU/s but my source database RU/s is set to 15000RU/s

Due to the Http 429 is there a way to see data integrity and find if any of the documents got corrupted.

Batch Upload completed 
--------------------------------------------------------------------- 
Inserted 4778 docs @ 326.09 writes/s, 8909.58 RU/s in 14.652323 sec
Average RU consumption per document: 27.32
---------------------------------------------------------------------

Summary of Batch 49 records retrieved 4778. Records Uploaded: 4778
Total records retrieved 528915. Total records uploaded 528915

**Comment by tamusjroyce** [comment]
You may want to check your partition index. Bottlenecks will occur if partitioning is not distributed.

429 means Cosmos rejected saving those documents. It is atomic / all or nothing, per-document. Documents should not get corrupted. Goes against normal document db to require multiple documents to depend on one-another to be consistent. Choose a larger document or a different database that has those guarantees.
